title: "Cuberite"
description: "A custom Minecraft compatible game server written in C++. It's a fast, lightweight, and awesome replacement for Vanilla."
exclude:
  - CNAME
  - README.md
sass:
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
permalink: /:categories/:title/
paginate: 4
paginate_path: /news/:num/
