baseurl: "/cuberite-redesign"
markdown: redcarpet
highlighter: pygments
permalink: /blog/:title/
paginate: 5
paginate_path: "/blog/page/:num/"
sass:
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
